### ISSUE TITLE
Improvements - Video

### ISSUE THREAD

**Issue by nidamunir** [drkPrince/tweet-to-image#1]
I want to take it to the next step.

- Support Multiple Tweets/images
- Select a User whose tweets we want
- Select a time period for tweets
- Select tweets for a timer period for a specific user
- Convert it into a video

What do you think?

**Comment by nidamunir** [comment]
Can we contribute together?

**Comment by drkPrince** [comment]
I like your ideas. But I see the possibility of exceeding twitter api limits, once the user base grows.
