### ISSUE TITLE
Change the app name

### ISSUE THREAD

**Issue by iqbalcrat** [drkPrince/tweet-to-image#2]
As told earlier, I already have a similar application with similar name https://twipix.co

Kindly change your app name.

**Comment by drkPrince** [comment]
Hi Iqbal, I didn't know about your app and I understand your concern. The thing is, I've been tested Covid+ and I'm running sick for the last few days. Rest assured, I'll change the name of my app as soon as I'm able to get back on my computer. I don't care of my app's name. Just give me 3..4 days. Hope you understand.

**Comment by iqbalcrat** [comment]
I'm sorry to hear that bro, please take care of your health.

**Comment by drkPrince** [comment]
@iqbalcrat Done.
